var searchData=
[
  ['page_20md_5fi_5f8hyper_5f8smac_5f8tmp_20i_20hyper_20smac_20tmp_0',['@page md_i_8hyper_8smac_8tmp i.hyper.smac.tmp',['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md34',1,'']]],
  ['parallel_20lut_1',['parallel lut',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md160',1,'After Parallel LUT'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md159',1,'Before Parallel LUT']]],
  ['parallel_20lut_20generation_2',['Parallel LUT Generation',['../md_i_8hyper_8smac.html#autotoc_md20',1,'']]],
  ['parallel_20lut_20generation_20for_20i_20hyper_20smac_3',['Parallel LUT Generation for i.hyper.smac',['../md_PARALLEL__LUT.html',1,'']]],
  ['parallel_20lut_20generation_20new_4',['Parallel LUT Generation (NEW)',['../md_i_8hyper_8smac.html#autotoc_md3',1,'']]],
  ['parallel_20lut_20generator_20module_20strong_20tt_20lib_20parallel_5flut_20py_20tt_5',['1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'']]],
  ['parallel_20lut_20generator_20module_20tt_20lib_20parallel_5flut_20py_20tt_6',['1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'']]],
  ['parallel_20lut_20implementation_20complete_20success_7',['🎯 Parallel LUT Implementation - COMPLETE SUCCESS',['../md_PARALLEL__LUT__FINAL.html',1,'']]],
  ['parallel_20lut_20implementation_20complete_20success_20strong_8',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['parallel_20lut_20implementation_20success_9',['✅ Parallel LUT Implementation SUCCESS',['../md_PARALLEL__LUT__SUCCESS.html',1,'']]],
  ['parallel_20lut_20implementation_20summary_10',['Parallel LUT Implementation Summary',['../md_PARALLEL__LUT__SUMMARY.html',1,'']]],
  ['parallel_20processing_11',['parallel processing',['../md_i_8hyper_8smac.html#autotoc_md9',1,'Advanced Configuration with Parallel Processing'],['../md_PROGRAMMER__MANUAL.html#autotoc_md229',1,'Parallel Processing']]],
  ['parallel_5flut_20py_20tt_12',['parallel_lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)']]],
  ['parameter_20options_13',['Parameter Options',['../md_PARALLEL__LUT.html#autotoc_md96',1,'']]],
  ['parameters_14',['parameters',['../md_i_8hyper_8smac.html#autotoc_md13',1,'Atmospheric Parameters'],['../md_i_8hyper_8smac.html#autotoc_md14',1,'Geometric Parameters'],['../md_i_8hyper_8smac.html#autotoc_md11',1,'PARAMETERS'],['../md_README.html#autotoc_md264',1,'Parameters'],['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md37',1,'Parameters'],['../md_i_8hyper_8smac.html#autotoc_md15',1,'Performance Parameters'],['../md_i_8hyper_8smac.html#autotoc_md12',1,'Required Parameters']]],
  ['paris_20january_15',['Continental urban temperate mid-winter (e.g. Paris, January)',['../md_README.html#autotoc_md258',1,'']]],
  ['peninsula_16',['Desert / arid land (Sahara, Arabian Peninsula)',['../md_README.html#autotoc_md256',1,'']]],
  ['per_20pixel_20h2o_20retrieval_17',['Per-Pixel H2O Retrieval',['../md_README.html#autotoc_md274',1,'']]],
  ['perfect_20coverage_18',['Example 1: Perfect Coverage',['../md_SMART__LUT__INTEGRATION.html#autotoc_md305',1,'']]],
  ['performance_19',['Performance',['../md_OPENCL__INTEGRATION.html#autotoc_md46',1,'']]],
  ['performance_20benefits_20',['performance benefits',['../md_README.html#autotoc_md268',1,'Performance Benefits'],['../md_PARALLEL__LUT.html#autotoc_md90',1,'Performance Benefits']]],
  ['performance_20impact_20achieved_20strong_21',['📊 &lt;strong&gt;Performance Impact Achieved&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md115',1,'']]],
  ['performance_20impact_20strong_22',['performance impact strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md182',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md158',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md136',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;']]],
  ['performance_20improvement_23',['Performance Improvement',['../md_SMART__LUT__INTEGRATION.html#autotoc_md302',1,'']]],
  ['performance_20improvements_24',['Expected Performance Improvements',['../md_OPENCL__SUMMARY.html#autotoc_md73',1,'']]],
  ['performance_20optimization_25',['performance optimization',['../md_i_8hyper_8smac.html#autotoc_md19',1,'PERFORMANCE OPTIMIZATION'],['../md_PROGRAMMER__MANUAL.html#autotoc_md227',1,'Performance Optimization']]],
  ['performance_20parameters_26',['Performance Parameters',['../md_i_8hyper_8smac.html#autotoc_md15',1,'']]],
  ['performance_20results_27',['📊 Performance Results',['../md_OPENCL__SUMMARY.html#autotoc_md71',1,'']]],
  ['performance_20tests_28',['Performance Tests',['../md_PROGRAMMER__MANUAL.html#autotoc_md226',1,'']]],
  ['performance_20tips_29',['Performance Tips',['../md_OPENCL__INTEGRATION.html#autotoc_md59',1,'']]],
  ['performance_20tuning_30',['performance tuning',['../md_PARALLEL__LUT.html#autotoc_md108',1,'Performance Tuning'],['../i_hyper_smac.html#i_hyper_smac_performance',1,'Performance Tuning']]],
  ['performance_20validation_31',['performance validation',['../md_PARALLEL__LUT__FINAL.html#autotoc_md148',1,'Performance Validation'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md194',1,'Performance Validation'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md172',1,'Performance Validation']]],
  ['performance_20validation_20✅_32',['Performance Validation ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md126',1,'']]],
  ['pipeline_33',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md275',1,'']]],
  ['pixel_20h2o_20retrieval_34',['Per-Pixel H2O Retrieval',['../md_README.html#autotoc_md274',1,'']]],
  ['potential_35',['Speedup Potential',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md183',1,'']]],
  ['pre_20generated_20coefficients_36',['Pre-generated Coefficients',['../md_README.html#autotoc_md277',1,'']]],
  ['precision_37',['Example 2: Insufficient Precision',['../md_SMART__LUT__INTEGRATION.html#autotoc_md306',1,'']]],
  ['prior_20and_20map_20estimate_38',['Surface Prior and MAP Estimate',['../md_README.html#autotoc_md291',1,'']]],
  ['problem_20solved_39',['Problem Solved',['../md_SMART__LUT__INTEGRATION.html#autotoc_md301',1,'']]],
  ['process_40',['Two-Stage Atmospheric Correction Process',['../md_i_8hyper_8smac.html#autotoc_md6',1,'']]],
  ['process_20management_41',['Process Management',['../md_PARALLEL__LUT.html#autotoc_md100',1,'']]],
  ['processing_42',['processing',['../md_i_8hyper_8smac.html#autotoc_md9',1,'Advanced Configuration with Parallel Processing'],['../md_i_8hyper_8smac.html#autotoc_md26',1,'Batch Processing'],['../md_OPENCL__SUMMARY.html#autotoc_md81',1,'CPU-Only Processing'],['../md_README.html#autotoc_md262',1,'Full ISOFIT-Inspired Processing'],['../md_OPENCL__SUMMARY.html#autotoc_md80',1,'Memory-Constrained Processing'],['../md_PROGRAMMER__MANUAL.html#autotoc_md229',1,'Parallel Processing']]],
  ['processing_20pipeline_43',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md275',1,'']]],
  ['programmatic_20usage_44',['Programmatic Usage',['../i_hyper_smac.html#i_hyper_smac_programmatic_example',1,'']]],
  ['programmer_20manual_45',['i.hyper.smac Programmer Manual',['../md_PROGRAMMER__MANUAL.html',1,'']]],
  ['project_20structure_46',['Project Structure',['../md_README.html#autotoc_md248',1,'']]],
  ['propagation_47',['Uncertainty Propagation',['../md_README.html#autotoc_md292',1,'']]],
  ['py_20tt_48',['py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_OPENCL__SUMMARY.html#autotoc_md67',1,'1. OpenCL Accelerator Module (&lt;tt&gt;lib/opencl_accelerator.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md155',1,'2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md180',1,'2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_README.html#autotoc_md278',1,'Generating Coefficients with &lt;tt&gt;smac_coef_generator.py&lt;/tt&gt;']]],
  ['pyopencl_20not_20found_49',['pyOpenCL not found',['../md_OPENCL__INTEGRATION.html#autotoc_md56',1,'']]]
];
