var searchData=
[
  ['i_20hyper_20smac_0',['i hyper smac',['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md36',1,'i.hyper.smac'],['../md_OPENCL__INTEGRATION.html',1,'OpenCL GPU Acceleration for i.hyper.smac'],['../md_PARALLEL__LUT.html',1,'Parallel LUT Generation for i.hyper.smac'],['../md_SMART__LUT__INTEGRATION.html',1,'Smart LUT Integration for i.hyper.smac']]],
  ['i_20hyper_20smac_20apply_20smac_20atmospheric_20correction_20to_20hyperspectral_20imagery_1',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['i_20hyper_20smac_20programmer_20manual_2',['i.hyper.smac Programmer Manual',['../md_PROGRAMMER__MANUAL.html',1,'']]],
  ['i_20hyper_20smac_20py_20tt_3',['i hyper smac py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)']]],
  ['i_20hyper_20smac_20smac_20atmospheric_20correction_20for_20hyperspectral_20data_4',['i.hyper.smac - SMAC Atmospheric Correction for Hyperspectral Data',['../md_README.html',1,'']]],
  ['i_20hyper_20smac_20tmp_5',['@page md_i_8hyper_8smac_8tmp i.hyper.smac.tmp',['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md34',1,'']]],
  ['i_20hyper_20smac_3a_20hyperspectral_20atmospheric_20correction_20module_6',['i.hyper.smac: Hyperspectral Atmospheric Correction Module',['../i_hyper_smac.html',1,'']]],
  ['imagery_7',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['imagery_20hyperspectral_20atmospheric_20correction_20smac_8',['keywords: [ imagery, hyperspectral, atmospheric correction, SMAC ]',['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md35',1,'']]],
  ['immediate_20benefits_9',['Immediate Benefits',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md196',1,'']]],
  ['immediate_20impact_10',['immediate impact',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md164',1,'Immediate Impact'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md140',1,'Immediate Impact'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md118',1,'Immediate Impact']]],
  ['impact_11',['impact',['../md_OPENCL__SUMMARY.html#autotoc_md87',1,'🎯 Impact'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md164',1,'Immediate Impact'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md140',1,'Immediate Impact'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md118',1,'Immediate Impact']]],
  ['impact_20achieved_20strong_12',['📊 &lt;strong&gt;Performance Impact Achieved&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md115',1,'']]],
  ['impact_20on_20users_20strong_13',['🎯 &lt;strong&gt;Impact on Users&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md195',1,'']]],
  ['impact_20strong_14',['impact strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md182',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md158',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md136',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;']]],
  ['impact_20summary_20strong_15',['🏆 &lt;strong&gt;Impact Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md130',1,'']]],
  ['implementation_16',['implementation',['../md_OPENCL__SUMMARY.html#autotoc_md74',1,'🛠️ Technical Implementation'],['../md_PARALLEL__LUT.html#autotoc_md92',1,'Implementation']]],
  ['implementation_20complete_17',['✅ Implementation Complete',['../md_OPENCL__SUMMARY.html#autotoc_md65',1,'']]],
  ['implementation_20complete_20strong_18',['✅ &lt;strong&gt;IMPLEMENTATION COMPLETE&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md177',1,'']]],
  ['implementation_20complete_20success_19',['🎯 Parallel LUT Implementation - COMPLETE SUCCESS',['../md_PARALLEL__LUT__FINAL.html',1,'']]],
  ['implementation_20complete_20success_20strong_20',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['implementation_20details_21',['Implementation Details',['../md_OPENCL__INTEGRATION.html#autotoc_md50',1,'']]],
  ['implementation_20status_20strong_22',['implementation status strong',['../md_PARALLEL__LUT__FINAL.html#autotoc_md134',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md113',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;']]],
  ['implementation_20steps_23',['Implementation Steps',['../md_SMART__LUT__INTEGRATION.html#autotoc_md311',1,'']]],
  ['implementation_20strong_24',['🛠️ &lt;strong&gt;Technical Implementation&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md185',1,'']]],
  ['implementation_20success_25',['✅ Parallel LUT Implementation SUCCESS',['../md_PARALLEL__LUT__SUCCESS.html',1,'']]],
  ['implementation_20summary_26',['Parallel LUT Implementation Summary',['../md_PARALLEL__LUT__SUMMARY.html',1,'']]],
  ['implementation_20summary_20strong_27',['🏆 &lt;strong&gt;Implementation Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md173',1,'']]],
  ['implemented_28',['🚀 What Was Implemented',['../md_OPENCL__SUMMARY.html#autotoc_md66',1,'']]],
  ['implemented_20strong_29',['implemented strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md116',1,'🎯 &lt;strong&gt;Technical Architecture Implemented&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md178',1,'🚀 &lt;strong&gt;What Was Implemented&lt;/strong&gt;']]],
  ['improvement_30',['Performance Improvement',['../md_SMART__LUT__INTEGRATION.html#autotoc_md302',1,'']]],
  ['improvements_31',['Expected Performance Improvements',['../md_OPENCL__SUMMARY.html#autotoc_md73',1,'']]],
  ['initialization_20fails_32',['OpenCL initialization fails',['../md_PROGRAMMER__MANUAL.html#autotoc_md234',1,'']]],
  ['inspired_20processing_33',['Full ISOFIT-Inspired Processing',['../md_README.html#autotoc_md262',1,'']]],
  ['inspired_20processing_20pipeline_34',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md275',1,'']]],
  ['installation_35',['installation',['../md_OPENCL__INTEGRATION.html#autotoc_md40',1,'Installation'],['../md_README.html#autotoc_md270',1,'Installation'],['../md_README.html#autotoc_md252',1,'Installation'],['../md_PROGRAMMER__MANUAL.html#autotoc_md207',1,'Installation'],['../md_README.html#autotoc_md254',1,'Manual Installation'],['../md_PROGRAMMER__MANUAL.html#autotoc_md210',1,'Module Installation']]],
  ['installation_20and_20setup_36',['🔧 Installation and Setup',['../md_OPENCL__SUMMARY.html#autotoc_md82',1,'']]],
  ['installation_20steps_37',['Installation Steps',['../md_OPENCL__SUMMARY.html#autotoc_md84',1,'']]],
  ['insufficient_20precision_38',['Example 2: Insufficient Precision',['../md_SMART__LUT__INTEGRATION.html#autotoc_md306',1,'']]],
  ['integration_39',['Module Integration',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md192',1,'']]],
  ['integration_20code_40',['Integration Code',['../md_SMART__LUT__INTEGRATION.html#autotoc_md303',1,'']]],
  ['integration_20for_20i_20hyper_20smac_41',['Smart LUT Integration for i.hyper.smac',['../md_SMART__LUT__INTEGRATION.html',1,'']]],
  ['integration_20status_42',['integration status',['../md_OPENCL__INTEGRATION.html#autotoc_md60',1,'Integration Status'],['../md_PARALLEL__LUT.html#autotoc_md102',1,'Integration Status']]],
  ['integration_20strong_20tt_20i_20hyper_20smac_20py_20tt_43',['3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'']]],
  ['integration_20strong_20tt_20lib_20lut_20py_20tt_44',['2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md155',1,'']]],
  ['integration_20summary_45',['OpenCL Integration Summary',['../md_OPENCL__SUMMARY.html',1,'']]],
  ['integration_20testing_20✅_46',['Integration Testing ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md127',1,'']]],
  ['integration_20tests_47',['Integration Tests',['../md_PROGRAMMER__MANUAL.html#autotoc_md225',1,'']]],
  ['integration_20tt_20i_20hyper_20smac_20py_20tt_48',['3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'']]],
  ['integration_20tt_20lib_20lut_20py_20tt_49',['2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md180',1,'']]],
  ['integration_20with_20main_20workflow_50',['3. Integration with Main Workflow',['../md_OPENCL__SUMMARY.html#autotoc_md69',1,'']]],
  ['inversion_206s_20style_51',['LUT Inversion (6S-style)',['../md_README.html#autotoc_md287',1,'']]],
  ['isofit_20inspired_20processing_52',['Full ISOFIT-Inspired Processing',['../md_README.html#autotoc_md262',1,'']]],
  ['isofit_20inspired_20processing_20pipeline_53',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md275',1,'']]],
  ['issues_54',['issues',['../md_PROGRAMMER__MANUAL.html#autotoc_md232',1,'Common Issues'],['../md_PARALLEL__LUT.html#autotoc_md107',1,'Common Issues'],['../md_OPENCL__INTEGRATION.html#autotoc_md55',1,'Common Issues'],['../i_hyper_smac.html#i_hyper_smac_common_issues',1,'Common Issues']]]
];
