var searchData=
[
  ['parallel_20lut_0',['parallel lut',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'After Parallel LUT'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md155',1,'Before Parallel LUT']]],
  ['parallel_20lut_20generation_1',['Parallel LUT Generation',['../md_i_8hyper_8smac.html#autotoc_md20',1,'']]],
  ['parallel_20lut_20generation_20for_20i_20hyper_20smac_2',['Parallel LUT Generation for i.hyper.smac',['../md_PARALLEL__LUT.html',1,'']]],
  ['parallel_20lut_20generation_20new_3',['Parallel LUT Generation (NEW)',['../md_i_8hyper_8smac.html#autotoc_md3',1,'']]],
  ['parallel_20lut_20generator_20module_20strong_20tt_20lib_20parallel_5flut_20py_20tt_4',['1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md150',1,'']]],
  ['parallel_20lut_20generator_20module_20tt_20lib_20parallel_5flut_20py_20tt_5',['1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md175',1,'']]],
  ['parallel_20lut_20implementation_20complete_20success_6',['🎯 Parallel LUT Implementation - COMPLETE SUCCESS',['../md_PARALLEL__LUT__FINAL.html',1,'']]],
  ['parallel_20lut_20implementation_20complete_20success_20strong_7',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['parallel_20lut_20implementation_20success_8',['✅ Parallel LUT Implementation SUCCESS',['../md_PARALLEL__LUT__SUCCESS.html',1,'']]],
  ['parallel_20lut_20implementation_20summary_9',['Parallel LUT Implementation Summary',['../md_PARALLEL__LUT__SUMMARY.html',1,'']]],
  ['parallel_20processing_10',['parallel processing',['../md_i_8hyper_8smac.html#autotoc_md9',1,'Advanced Configuration with Parallel Processing'],['../md_PROGRAMMER__MANUAL.html#autotoc_md225',1,'Parallel Processing']]],
  ['parallel_5flut_20py_20tt_11',['parallel_lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md150',1,'1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md175',1,'1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)']]],
  ['parameter_20options_12',['Parameter Options',['../md_PARALLEL__LUT.html#autotoc_md92',1,'']]],
  ['parameters_13',['parameters',['../md_i_8hyper_8smac.html#autotoc_md13',1,'Atmospheric Parameters'],['../md_i_8hyper_8smac.html#autotoc_md14',1,'Geometric Parameters'],['../md_i_8hyper_8smac.html#autotoc_md11',1,'PARAMETERS'],['../md_README.html#autotoc_md260',1,'Parameters'],['../md_i_8hyper_8smac.html#autotoc_md15',1,'Performance Parameters'],['../md_i_8hyper_8smac.html#autotoc_md12',1,'Required Parameters']]],
  ['paris_20january_14',['Continental urban temperate mid-winter (e.g. Paris, January)',['../md_README.html#autotoc_md254',1,'']]],
  ['peninsula_15',['Desert / arid land (Sahara, Arabian Peninsula)',['../md_README.html#autotoc_md252',1,'']]],
  ['per_20pixel_20h2o_20retrieval_16',['Per-Pixel H2O Retrieval',['../md_README.html#autotoc_md270',1,'']]],
  ['perfect_20coverage_17',['Example 1: Perfect Coverage',['../md_SMART__LUT__INTEGRATION.html#autotoc_md301',1,'']]],
  ['performance_18',['Performance',['../md_OPENCL__INTEGRATION.html#autotoc_md42',1,'']]],
  ['performance_20benefits_19',['performance benefits',['../md_PARALLEL__LUT.html#autotoc_md86',1,'Performance Benefits'],['../md_README.html#autotoc_md264',1,'Performance Benefits']]],
  ['performance_20impact_20achieved_20strong_20',['📊 &lt;strong&gt;Performance Impact Achieved&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md111',1,'']]],
  ['performance_20impact_20strong_21',['performance impact strong',['../md_PARALLEL__LUT__FINAL.html#autotoc_md132',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md178',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;']]],
  ['performance_20improvement_22',['Performance Improvement',['../md_SMART__LUT__INTEGRATION.html#autotoc_md298',1,'']]],
  ['performance_20improvements_23',['Expected Performance Improvements',['../md_OPENCL__SUMMARY.html#autotoc_md69',1,'']]],
  ['performance_20optimization_24',['performance optimization',['../md_i_8hyper_8smac.html#autotoc_md19',1,'PERFORMANCE OPTIMIZATION'],['../md_PROGRAMMER__MANUAL.html#autotoc_md223',1,'Performance Optimization']]],
  ['performance_20parameters_25',['Performance Parameters',['../md_i_8hyper_8smac.html#autotoc_md15',1,'']]],
  ['performance_20results_26',['📊 Performance Results',['../md_OPENCL__SUMMARY.html#autotoc_md67',1,'']]],
  ['performance_20tests_27',['Performance Tests',['../md_PROGRAMMER__MANUAL.html#autotoc_md222',1,'']]],
  ['performance_20tips_28',['Performance Tips',['../md_OPENCL__INTEGRATION.html#autotoc_md55',1,'']]],
  ['performance_20tuning_29',['performance tuning',['../i_hyper_smac.html#i_hyper_smac_performance',1,'Performance Tuning'],['../md_PARALLEL__LUT.html#autotoc_md104',1,'Performance Tuning']]],
  ['performance_20validation_30',['performance validation',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md190',1,'Performance Validation'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md168',1,'Performance Validation'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md144',1,'Performance Validation']]],
  ['performance_20validation_20✅_31',['Performance Validation ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md122',1,'']]],
  ['pipeline_32',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md271',1,'']]],
  ['pixel_20h2o_20retrieval_33',['Per-Pixel H2O Retrieval',['../md_README.html#autotoc_md270',1,'']]],
  ['potential_34',['Speedup Potential',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'']]],
  ['pre_20generated_20coefficients_35',['Pre-generated Coefficients',['../md_README.html#autotoc_md273',1,'']]],
  ['precision_36',['Example 2: Insufficient Precision',['../md_SMART__LUT__INTEGRATION.html#autotoc_md302',1,'']]],
  ['prior_20and_20map_20estimate_37',['Surface Prior and MAP Estimate',['../md_README.html#autotoc_md287',1,'']]],
  ['problem_20solved_38',['Problem Solved',['../md_SMART__LUT__INTEGRATION.html#autotoc_md297',1,'']]],
  ['process_39',['Two-Stage Atmospheric Correction Process',['../md_i_8hyper_8smac.html#autotoc_md6',1,'']]],
  ['process_20management_40',['Process Management',['../md_PARALLEL__LUT.html#autotoc_md96',1,'']]],
  ['processing_41',['processing',['../md_i_8hyper_8smac.html#autotoc_md9',1,'Advanced Configuration with Parallel Processing'],['../md_i_8hyper_8smac.html#autotoc_md26',1,'Batch Processing'],['../md_OPENCL__SUMMARY.html#autotoc_md77',1,'CPU-Only Processing'],['../md_README.html#autotoc_md258',1,'Full ISOFIT-Inspired Processing'],['../md_OPENCL__SUMMARY.html#autotoc_md76',1,'Memory-Constrained Processing'],['../md_PROGRAMMER__MANUAL.html#autotoc_md225',1,'Parallel Processing']]],
  ['processing_20pipeline_42',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md271',1,'']]],
  ['programmatic_20usage_43',['Programmatic Usage',['../i_hyper_smac.html#i_hyper_smac_programmatic_example',1,'']]],
  ['programmer_20manual_44',['i.hyper.smac Programmer Manual',['../md_PROGRAMMER__MANUAL.html',1,'']]],
  ['project_20structure_45',['Project Structure',['../md_README.html#autotoc_md244',1,'']]],
  ['propagation_46',['Uncertainty Propagation',['../md_README.html#autotoc_md288',1,'']]],
  ['py_20tt_47',['py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md150',1,'1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_OPENCL__SUMMARY.html#autotoc_md63',1,'1. OpenCL Accelerator Module (&lt;tt&gt;lib/opencl_accelerator.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md175',1,'1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md151',1,'2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md176',1,'2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md177',1,'3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_README.html#autotoc_md274',1,'Generating Coefficients with &lt;tt&gt;smac_coef_generator.py&lt;/tt&gt;']]],
  ['pyopencl_20not_20found_48',['pyOpenCL not found',['../md_OPENCL__INTEGRATION.html#autotoc_md52',1,'']]]
];
