var searchData=
[
  ['cache_20management_0',['Cache Management',['../md_SMART__LUT__INTEGRATION.html#autotoc_md304',1,'']]],
  ['calibration_1',['Aerosol Spectral Calibration',['../md_README.html#autotoc_md285',1,'']]],
  ['categories_2',['Test Categories',['../md_PROGRAMMER__MANUAL.html#autotoc_md219',1,'']]],
  ['changes_3',['Submitting Changes',['../md_PROGRAMMER__MANUAL.html#autotoc_md236',1,'']]],
  ['checking_20and_20regeneration_4',['Dynamic LUT Coverage Checking and Regeneration',['../md_SMART__LUT__INTEGRATION.html#autotoc_md296',1,'']]],
  ['classes_5',['classes',['../md_PROGRAMMER__MANUAL.html#autotoc_md213',1,'LUT Classes'],['../i_hyper_smac.html#i_hyper_smac_lut_classes',1,'LUT Classes'],['../i_hyper_smac.html#i_hyper_smac_smart_lut_classes',1,'Smart LUT Classes']]],
  ['coastal_20temperate_20mid_20summer_20e_20g_20mediterranean_20july_6',['Coastal temperate mid-summer (e.g. Mediterranean, July)',['../md_README.html#autotoc_md255',1,'']]],
  ['code_7',['Integration Code',['../md_SMART__LUT__INTEGRATION.html#autotoc_md299',1,'']]],
  ['code_20style_8',['Code Style',['../md_PROGRAMMER__MANUAL.html#autotoc_md235',1,'']]],
  ['coefficient_20generation_9',['SMAC Coefficient Generation',['../md_README.html#autotoc_md272',1,'']]],
  ['coefficients_10',['Pre-generated Coefficients',['../md_README.html#autotoc_md273',1,'']]],
  ['coefficients_20with_20tt_20smac_5fcoef_5fgenerator_20py_20tt_11',['Generating Coefficients with &lt;tt&gt;smac_coef_generator.py&lt;/tt&gt;',['../md_README.html#autotoc_md274',1,'']]],
  ['combined_20with_20opencl_12',['Combined with OpenCL',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md165',1,'']]],
  ['command_20line_20options_13',['Command Line Options',['../md_PARALLEL__LUT.html#autotoc_md91',1,'']]],
  ['common_20issues_14',['common issues',['../md_PROGRAMMER__MANUAL.html#autotoc_md228',1,'Common Issues'],['../md_OPENCL__INTEGRATION.html#autotoc_md51',1,'Common Issues'],['../md_PARALLEL__LUT.html#autotoc_md103',1,'Common Issues'],['../i_hyper_smac.html#i_hyper_smac_common_issues',1,'Common Issues']]],
  ['compatibility_15',['Compatibility',['../md_i_8hyper_8smac.html#autotoc_md30',1,'']]],
  ['complete_16',['✅ Implementation Complete',['../md_OPENCL__SUMMARY.html#autotoc_md61',1,'']]],
  ['complete_20solution_20delivered_20strong_17',['🚀 &lt;strong&gt;Complete Solution Delivered&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md110',1,'']]],
  ['complete_20strong_18',['complete strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md173',1,'✅ &lt;strong&gt;IMPLEMENTATION COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md171',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md125',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md146',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;']]],
  ['complete_20success_19',['🎯 Parallel LUT Implementation - COMPLETE SUCCESS',['../md_PARALLEL__LUT__FINAL.html',1,'']]],
  ['complete_20success_20strong_20',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['components_21',['Core Components',['../md_PARALLEL__LUT.html#autotoc_md89',1,'']]],
  ['configuration_22',['configuration',['../md_i_8hyper_8smac.html#autotoc_md25',1,'Advanced Configuration'],['../i_hyper_smac.html#i_hyper_smac_configuration',1,'Configuration'],['../md_i_8hyper_8smac.html#autotoc_md16',1,'Sensor Configuration']]],
  ['configuration_20options_23',['configuration options',['../md_OPENCL__SUMMARY.html#autotoc_md66',1,'4. Configuration Options'],['../md_SMART__LUT__INTEGRATION.html#autotoc_md305',1,'Configuration Options'],['../md_OPENCL__INTEGRATION.html#autotoc_md41',1,'Configuration Options']]],
  ['configuration_20with_20parallel_20processing_24',['Advanced Configuration with Parallel Processing',['../md_i_8hyper_8smac.html#autotoc_md9',1,'']]],
  ['congo_25',['Tropical rainforest (Amazon, Congo)',['../md_README.html#autotoc_md253',1,'']]],
  ['constrained_20processing_26',['Memory-Constrained Processing',['../md_OPENCL__SUMMARY.html#autotoc_md76',1,'']]],
  ['contents_27',['Table of Contents',['../md_PROGRAMMER__MANUAL.html#autotoc_md200',1,'']]],
  ['continental_20urban_20temperate_20mid_20winter_20e_20g_20paris_20january_28',['Continental urban temperate mid-winter (e.g. Paris, January)',['../md_README.html#autotoc_md254',1,'']]],
  ['continuum_20accuracy_29',['SWIR H2O Continuum Accuracy',['../md_README.html#autotoc_md286',1,'']]],
  ['continuum_20removal_20band_20depth_30',['WVC Estimation (Continuum-Removal Band Depth)',['../md_README.html#autotoc_md290',1,'']]],
  ['contributing_31',['Contributing',['../md_PROGRAMMER__MANUAL.html#autotoc_md233',1,'']]],
  ['control_32',['Quality Control',['../i_hyper_smac.html#i_hyper_smac_quality',1,'']]],
  ['copyright_33',['COPYRIGHT',['../md_i_8hyper_8smac.html#autotoc_md33',1,'']]],
  ['core_20architecture_34',['core architecture',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md182',1,'Core Architecture'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md158',1,'Core Architecture']]],
  ['core_20components_35',['Core Components',['../md_PARALLEL__LUT.html#autotoc_md89',1,'']]],
  ['core_20features_20delivered_20strong_36',['🚀 &lt;strong&gt;Core Features Delivered&lt;/strong&gt;',['../md_PARALLEL__LUT__FINAL.html#autotoc_md131',1,'']]],
  ['correction_37',['correction',['../md_README.html#autotoc_md284',1,'Adjacency Effect Correction'],['../md_i_8hyper_8smac.html#autotoc_md8',1,'Basic Atmospheric Correction'],['../md_README.html#autotoc_md268',1,'LUT Atmospheric Correction'],['../md_i_8hyper_8smac.html#autotoc_md4',1,'OpenCL Acceleration for Atmospheric Correction']]],
  ['correction_20for_20hyperspectral_20data_38',['i.hyper.smac - SMAC Atmospheric Correction for Hyperspectral Data',['../md_README.html',1,'']]],
  ['correction_20module_39',['i.hyper.smac: Hyperspectral Atmospheric Correction Module',['../i_hyper_smac.html',1,'']]],
  ['correction_20process_40',['Two-Stage Atmospheric Correction Process',['../md_i_8hyper_8smac.html#autotoc_md6',1,'']]],
  ['correction_20to_20hyperspectral_20imagery_41',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['coverage_42',['coverage',['../md_SMART__LUT__INTEGRATION.html#autotoc_md301',1,'Example 1: Perfect Coverage'],['../md_PROGRAMMER__MANUAL.html#autotoc_md237',1,'Test Coverage']]],
  ['coverage_20checking_20and_20regeneration_43',['Dynamic LUT Coverage Checking and Regeneration',['../md_SMART__LUT__INTEGRATION.html#autotoc_md296',1,'']]],
  ['cpu_20only_20processing_44',['CPU-Only Processing',['../md_OPENCL__SUMMARY.html#autotoc_md77',1,'']]],
  ['created_20strong_45',['created strong',['../md_PARALLEL__LUT__FINAL.html#autotoc_md141',1,'📚 &lt;strong&gt;Documentation Created&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md119',1,'📚 &lt;strong&gt;Documentation Created&lt;/strong&gt;']]],
  ['credits_46',['Credits',['../i_hyper_smac.html#i_hyper_smac_credits',1,'']]]
];
