var searchData=
[
  ['land_20sahara_20arabian_20peninsula_0',['Desert / arid land (Sahara, Arabian Peninsula)',['../md_README.html#autotoc_md252',1,'']]],
  ['legacy_20methods_1',['Legacy Methods',['../md_README.html#autotoc_md259',1,'']]],
  ['lib_20lut_20py_20tt_2',['lib lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md151',1,'2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md176',1,'2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)']]],
  ['lib_20opencl_5faccelerator_20py_20tt_3',['1. OpenCL Accelerator Module (&lt;tt&gt;lib/opencl_accelerator.py&lt;/tt&gt;)',['../md_OPENCL__SUMMARY.html#autotoc_md63',1,'']]],
  ['lib_20parallel_5flut_20py_20tt_4',['lib parallel_lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md150',1,'1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md175',1,'1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)']]],
  ['libradtran_20not_20found_5',['libRadtran not found',['../md_PROGRAMMER__MANUAL.html#autotoc_md229',1,'']]],
  ['library_20api_6',['Library API',['../md_README.html#autotoc_md279',1,'']]],
  ['license_7',['license',['../md_PROGRAMMER__MANUAL.html#autotoc_md239',1,'License'],['../i_hyper_smac.html#i_hyper_smac_license',1,'License'],['../md_README.html#autotoc_md293',1,'License']]],
  ['line_20options_8',['Command Line Options',['../md_PARALLEL__LUT.html#autotoc_md91',1,'']]],
  ['logic_9',['Auto-Detection Logic',['../md_PARALLEL__LUT.html#autotoc_md93',1,'']]],
  ['long_20term_20research_10',['Long Term (Research)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md197',1,'']]],
  ['lut_11',['lut',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'After Parallel LUT'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md155',1,'Before Parallel LUT']]],
  ['lut_20atmospheric_20correction_12',['LUT Atmospheric Correction',['../md_README.html#autotoc_md268',1,'']]],
  ['lut_20behavior_20examples_13',['Smart LUT Behavior Examples',['../md_SMART__LUT__INTEGRATION.html#autotoc_md300',1,'']]],
  ['lut_20classes_14',['lut classes',['../i_hyper_smac.html#i_hyper_smac_lut_classes',1,'LUT Classes'],['../md_PROGRAMMER__MANUAL.html#autotoc_md213',1,'LUT Classes'],['../i_hyper_smac.html#i_hyper_smac_smart_lut_classes',1,'Smart LUT Classes']]],
  ['lut_20coverage_20checking_20and_20regeneration_15',['Dynamic LUT Coverage Checking and Regeneration',['../md_SMART__LUT__INTEGRATION.html#autotoc_md296',1,'']]],
  ['lut_20generation_16',['lut generation',['../md_README.html#autotoc_md269',1,'LUT Generation'],['../md_i_8hyper_8smac.html#autotoc_md28',1,'LUT Generation'],['../md_i_8hyper_8smac.html#autotoc_md20',1,'Parallel LUT Generation']]],
  ['lut_20generation_20for_20i_20hyper_20smac_17',['Parallel LUT Generation for i.hyper.smac',['../md_PARALLEL__LUT.html',1,'']]],
  ['lut_20generation_20new_18',['Parallel LUT Generation (NEW)',['../md_i_8hyper_8smac.html#autotoc_md3',1,'']]],
  ['lut_20generator_20module_20strong_20tt_20lib_20parallel_5flut_20py_20tt_19',['1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md150',1,'']]],
  ['lut_20generator_20module_20tt_20lib_20parallel_5flut_20py_20tt_20',['1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md175',1,'']]],
  ['lut_20implementation_20complete_20success_21',['🎯 Parallel LUT Implementation - COMPLETE SUCCESS',['../md_PARALLEL__LUT__FINAL.html',1,'']]],
  ['lut_20implementation_20complete_20success_20strong_22',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['lut_20implementation_20success_23',['✅ Parallel LUT Implementation SUCCESS',['../md_PARALLEL__LUT__SUCCESS.html',1,'']]],
  ['lut_20implementation_20summary_24',['Parallel LUT Implementation Summary',['../md_PARALLEL__LUT__SUMMARY.html',1,'']]],
  ['lut_20integration_20for_20i_20hyper_20smac_25',['Smart LUT Integration for i.hyper.smac',['../md_SMART__LUT__INTEGRATION.html',1,'']]],
  ['lut_20inversion_206s_20style_26',['LUT Inversion (6S-style)',['../md_README.html#autotoc_md283',1,'']]],
  ['lut_20module_20integration_20strong_20tt_20lib_20lut_20py_20tt_27',['2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md151',1,'']]],
  ['lut_20module_20integration_20tt_20lib_20lut_20py_20tt_28',['2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md176',1,'']]],
  ['lut_20py_20tt_29',['lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md151',1,'2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md176',1,'2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)']]],
  ['lut_20system_30',['lut system',['../md_PROGRAMMER__MANUAL.html#autotoc_md224',1,'Smart LUT System'],['../i_hyper_smac.html#i_hyper_smac_smart_lut',1,'Smart LUT System']]]
];
