var searchData=
[
  ['accelerated_20kernels_0',['2. GPU-Accelerated Kernels',['../md_OPENCL__SUMMARY.html#autotoc_md64',1,'']]],
  ['acceleration_1',['acceleration',['../md_OPENCL__SUMMARY.html#autotoc_md75',1,'Basic GPU Acceleration'],['../md_i_8hyper_8smac.html#autotoc_md22',1,'GPU Acceleration'],['../md_i_8hyper_8smac.html#autotoc_md10',1,'GPU Acceleration'],['../i_hyper_smac.html#i_hyper_smac_opencl',1,'OpenCL Acceleration'],['../md_PROGRAMMER__MANUAL.html#autotoc_md226',1,'OpenCL Acceleration'],['../md_README.html#autotoc_md263',1,'OpenCL GPU Acceleration']]],
  ['acceleration_20for_20atmospheric_20correction_2',['OpenCL Acceleration for Atmospheric Correction',['../md_i_8hyper_8smac.html#autotoc_md4',1,'']]],
  ['acceleration_20for_20i_20hyper_20smac_3',['OpenCL GPU Acceleration for i.hyper.smac',['../md_OPENCL__INTEGRATION.html',1,'']]],
  ['accelerator_20module_20tt_20lib_20opencl_5faccelerator_20py_20tt_4',['1. OpenCL Accelerator Module (&lt;tt&gt;lib/opencl_accelerator.py&lt;/tt&gt;)',['../md_OPENCL__SUMMARY.html#autotoc_md63',1,'']]],
  ['accomplished_20strong_5',['accomplished strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md148',1,'🎯 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md129',1,'📋 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md108',1,'📋 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;']]],
  ['accuracy_6',['SWIR H2O Continuum Accuracy',['../md_README.html#autotoc_md286',1,'']]],
  ['achieved_7',['Transformation Achieved',['../md_PARALLEL__LUT__FINAL.html#autotoc_md133',1,'']]],
  ['achieved_20strong_8',['📊 &lt;strong&gt;Performance Impact Achieved&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md111',1,'']]],
  ['achievement_20strong_9',['achievement strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md127',1,'🎊 &lt;strong&gt;Technical Achievement&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md157',1,'🚀 &lt;strong&gt;Technical Achievement&lt;/strong&gt;']]],
  ['achievement_20summary_20strong_10',['achievement summary strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md198',1,'🏆 &lt;strong&gt;Achievement Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md124',1,'🏆 &lt;strong&gt;Final Achievement Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md145',1,'🏆 &lt;strong&gt;Final Achievement Summary&lt;/strong&gt;']]],
  ['addon_11',['As GRASS GIS Addon',['../md_README.html#autotoc_md249',1,'']]],
  ['adjacency_20effect_20correction_12',['Adjacency Effect Correction',['../md_README.html#autotoc_md284',1,'']]],
  ['advanced_20configuration_13',['Advanced Configuration',['../md_i_8hyper_8smac.html#autotoc_md25',1,'']]],
  ['advanced_20configuration_20with_20parallel_20processing_14',['Advanced Configuration with Parallel Processing',['../md_i_8hyper_8smac.html#autotoc_md9',1,'']]],
  ['advanced_20options_15',['Advanced Options',['../md_i_8hyper_8smac.html#autotoc_md17',1,'']]],
  ['advanced_20usage_16',['advanced usage',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md164',1,'Advanced Usage'],['../i_hyper_smac.html#i_hyper_smac_advanced_example',1,'Advanced Usage'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md186',1,'Advanced Usage'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md140',1,'Advanced Usage'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md118',1,'Advanced Usage']]],
  ['aerosol_20optical_20depth_20estimation_17',['Aerosol Optical Depth Estimation',['../i_hyper_smac.html#i_hyper_smac_aod_estimation',1,'']]],
  ['aerosol_20spectral_20calibration_18',['Aerosol Spectral Calibration',['../md_README.html#autotoc_md285',1,'']]],
  ['after_20parallel_20lut_19',['After Parallel LUT',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'']]],
  ['algorithm_20',['AOD Estimation (Dark Target Algorithm)',['../md_README.html#autotoc_md289',1,'']]],
  ['algorithm_20details_21',['Algorithm Details',['../md_README.html#autotoc_md281',1,'']]],
  ['algorithms_22',['Algorithms',['../i_hyper_smac.html#i_hyper_smac_algorithms',1,'']]],
  ['also_23',['also',['../md_README.html#autotoc_md294',1,'See Also'],['../md_i_8hyper_8smac.html#autotoc_md32',1,'SEE ALSO']]],
  ['amazon_20congo_24',['Tropical rainforest (Amazon, Congo)',['../md_README.html#autotoc_md253',1,'']]],
  ['and_20map_20estimate_25',['Surface Prior and MAP Estimate',['../md_README.html#autotoc_md287',1,'']]],
  ['and_20regeneration_26',['Dynamic LUT Coverage Checking and Regeneration',['../md_SMART__LUT__INTEGRATION.html#autotoc_md296',1,'']]],
  ['and_20setup_27',['🔧 Installation and Setup',['../md_OPENCL__SUMMARY.html#autotoc_md78',1,'']]],
  ['and_20testing_20strong_28',['4. &lt;strong&gt;Documentation and Testing&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md153',1,'']]],
  ['aod_20estimation_20dark_20target_20algorithm_29',['AOD Estimation (Dark Target Algorithm)',['../md_README.html#autotoc_md289',1,'']]],
  ['api_30',['Library API',['../md_README.html#autotoc_md279',1,'']]],
  ['api_20reference_31',['api reference',['../i_hyper_smac.html#i_hyper_smac_api',1,'API Reference'],['../md_PROGRAMMER__MANUAL.html#autotoc_md210',1,'API Reference']]],
  ['apply_20smac_20atmospheric_20correction_20to_20hyperspectral_20imagery_32',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['apply_5flut_5fcorrection_20tt_33',['&lt;tt&gt;apply_lut_correction()&lt;/tt&gt;',['../md_PROGRAMMER__MANUAL.html#autotoc_md212',1,'']]],
  ['arabian_20peninsula_34',['Desert / arid land (Sahara, Arabian Peninsula)',['../md_README.html#autotoc_md252',1,'']]],
  ['architecture_35',['architecture',['../i_hyper_smac.html#i_hyper_smac_architecture',1,'Architecture'],['../md_i_8hyper_8smac.html#autotoc_md5',1,'ARCHITECTURE'],['../md_PROGRAMMER__MANUAL.html#autotoc_md207',1,'Architecture'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md182',1,'Core Architecture'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md158',1,'Core Architecture'],['../md_PROGRAMMER__MANUAL.html#autotoc_md208',1,'System Architecture'],['../i_hyper_smac.html#i_hyper_smac_arch_overview',1,'System Architecture'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md134',1,'Technical Architecture']]],
  ['architecture_20implemented_20strong_36',['🎯 &lt;strong&gt;Technical Architecture Implemented&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md112',1,'']]],
  ['arctic_20mid_20summer_20—_20tundra_20boreal_37',['Sub-arctic mid-summer — tundra / boreal',['../md_README.html#autotoc_md257',1,'']]],
  ['arctic_20mid_20winter_20—_20boreal_20forest_20under_20snow_38',['Sub-arctic mid-winter — boreal forest under snow',['../md_README.html#autotoc_md256',1,'']]],
  ['arid_20land_20sahara_20arabian_20peninsula_39',['Desert / arid land (Sahara, Arabian Peninsula)',['../md_README.html#autotoc_md252',1,'']]],
  ['as_20grass_20gis_20addon_40',['As GRASS GIS Addon',['../md_README.html#autotoc_md249',1,'']]],
  ['at_201nm_20resolution_41',['Batch generation at 1nm resolution',['../md_README.html#autotoc_md277',1,'']]],
  ['atmospheric_20correction_42',['atmospheric correction',['../md_i_8hyper_8smac.html#autotoc_md8',1,'Basic Atmospheric Correction'],['../md_README.html#autotoc_md268',1,'LUT Atmospheric Correction'],['../md_i_8hyper_8smac.html#autotoc_md4',1,'OpenCL Acceleration for Atmospheric Correction']]],
  ['atmospheric_20correction_20for_20hyperspectral_20data_43',['i.hyper.smac - SMAC Atmospheric Correction for Hyperspectral Data',['../md_README.html',1,'']]],
  ['atmospheric_20correction_20module_44',['i.hyper.smac: Hyperspectral Atmospheric Correction Module',['../i_hyper_smac.html',1,'']]],
  ['atmospheric_20correction_20process_45',['Two-Stage Atmospheric Correction Process',['../md_i_8hyper_8smac.html#autotoc_md6',1,'']]],
  ['atmospheric_20correction_20to_20hyperspectral_20imagery_46',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['atmospheric_20parameters_47',['Atmospheric Parameters',['../md_i_8hyper_8smac.html#autotoc_md13',1,'']]],
  ['atmosphericlut_20tt_48',['&lt;tt&gt;AtmosphericLUT&lt;/tt&gt;',['../md_PROGRAMMER__MANUAL.html#autotoc_md214',1,'']]],
  ['authors_49',['authors',['../md_i_8hyper_8smac.html#autotoc_md31',1,'AUTHORS'],['../md_README.html#autotoc_md292',1,'Authors']]],
  ['auto_20detection_50',['Basic Usage with Auto-Detection',['../md_i_8hyper_8smac.html#autotoc_md24',1,'']]],
  ['auto_20detection_20logic_51',['Auto-Detection Logic',['../md_PARALLEL__LUT.html#autotoc_md93',1,'']]]
];
