var searchData=
[
  ['main_20functions_0',['main functions',['../md_PROGRAMMER__MANUAL.html#autotoc_md215',1,'Main Functions'],['../i_hyper_smac.html#i_hyper_smac_main_functions',1,'Main Functions']]],
  ['main_20script_20integration_20strong_20tt_20i_20hyper_20smac_20py_20tt_1',['3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'']]],
  ['main_20script_20integration_20tt_20i_20hyper_20smac_20py_20tt_2',['3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'']]],
  ['main_20workflow_3',['3. Integration with Main Workflow',['../md_OPENCL__SUMMARY.html#autotoc_md69',1,'']]],
  ['management_4',['management',['../md_SMART__LUT__INTEGRATION.html#autotoc_md308',1,'Cache Management'],['../md_OPENCL__INTEGRATION.html#autotoc_md53',1,'Memory Management'],['../md_PARALLEL__LUT.html#autotoc_md100',1,'Process Management']]],
  ['manual_5',['i.hyper.smac Programmer Manual',['../md_PROGRAMMER__MANUAL.html',1,'']]],
  ['manual_20installation_6',['Manual Installation',['../md_README.html#autotoc_md254',1,'']]],
  ['manual_20testing_7',['Manual Testing',['../md_PARALLEL__LUT.html#autotoc_md105',1,'']]],
  ['map_20estimate_8',['Surface Prior and MAP Estimate',['../md_README.html#autotoc_md291',1,'']]],
  ['md_5fi_5f8hyper_5f8smac_5f8tmp_20i_20hyper_20smac_20tmp_9',['@page md_i_8hyper_8smac_8tmp i.hyper.smac.tmp',['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md34',1,'']]],
  ['mediterranean_20july_10',['Coastal temperate mid-summer (e.g. Mediterranean, July)',['../md_README.html#autotoc_md259',1,'']]],
  ['memory_20constrained_20processing_11',['Memory-Constrained Processing',['../md_OPENCL__SUMMARY.html#autotoc_md80',1,'']]],
  ['memory_20errors_12',['memory errors',['../md_OPENCL__INTEGRATION.html#autotoc_md58',1,'Memory errors'],['../md_PROGRAMMER__MANUAL.html#autotoc_md235',1,'Memory errors']]],
  ['memory_20management_13',['Memory Management',['../md_OPENCL__INTEGRATION.html#autotoc_md53',1,'']]],
  ['memory_20optimization_14',['memory optimization',['../md_OPENCL__INTEGRATION.html#autotoc_md49',1,'Memory Optimization'],['../md_PARALLEL__LUT.html#autotoc_md99',1,'Memory Optimization'],['../md_OPENCL__SUMMARY.html#autotoc_md76',1,'Memory Optimization'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md184',1,'Memory Optimization']]],
  ['memory_20requirements_15',['Memory Requirements',['../md_i_8hyper_8smac.html#autotoc_md29',1,'']]],
  ['met_16',['met',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md119',1,'System Requirements Met'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md141',1,'System Requirements Met']]],
  ['methods_17',['Legacy Methods',['../md_README.html#autotoc_md263',1,'']]],
  ['mid_20summer_20—_20tundra_20boreal_18',['Sub-arctic mid-summer — tundra / boreal',['../md_README.html#autotoc_md261',1,'']]],
  ['mid_20summer_20e_20g_20mediterranean_20july_19',['Coastal temperate mid-summer (e.g. Mediterranean, July)',['../md_README.html#autotoc_md259',1,'']]],
  ['mid_20winter_20—_20boreal_20forest_20under_20snow_20',['Sub-arctic mid-winter — boreal forest under snow',['../md_README.html#autotoc_md260',1,'']]],
  ['mid_20winter_20e_20g_20paris_20january_21',['Continental urban temperate mid-winter (e.g. Paris, January)',['../md_README.html#autotoc_md258',1,'']]],
  ['mission_20accomplished_20strong_22',['mission accomplished strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'🎯 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md133',1,'📋 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md112',1,'📋 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;']]],
  ['mission_20status_3a_20complete_20strong_23',['mission status: complete strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md175',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md150',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md129',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;']]],
  ['mode_24',['mode',['../i_hyper_smac.html#i_hyper_smac_debug_mode',1,'Debug Mode'],['../md_PROGRAMMER__MANUAL.html#autotoc_md236',1,'Debug Mode']]],
  ['module_25',['i.hyper.smac: Hyperspectral Atmospheric Correction Module',['../i_hyper_smac.html',1,'']]],
  ['module_20installation_26',['Module Installation',['../md_PROGRAMMER__MANUAL.html#autotoc_md210',1,'']]],
  ['module_20integration_27',['Module Integration',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md192',1,'']]],
  ['module_20integration_20strong_20tt_20lib_20lut_20py_20tt_28',['2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md155',1,'']]],
  ['module_20integration_20tt_20lib_20lut_20py_20tt_29',['2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md180',1,'']]],
  ['module_20strong_20tt_20lib_20parallel_5flut_20py_20tt_30',['1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'']]],
  ['module_20tests_31',['module tests',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md171',1,'Module Tests'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md147',1,'Module Tests']]],
  ['module_20tests_20✅_32',['Module Tests ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md125',1,'']]],
  ['module_20tt_20lib_20opencl_5faccelerator_20py_20tt_33',['1. OpenCL Accelerator Module (&lt;tt&gt;lib/opencl_accelerator.py&lt;/tt&gt;)',['../md_OPENCL__SUMMARY.html#autotoc_md67',1,'']]],
  ['module_20tt_20lib_20parallel_5flut_20py_20tt_34',['1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'']]]
];
