var searchData=
[
  ['table_20of_20contents_0',['Table of Contents',['../md_PROGRAMMER__MANUAL.html#autotoc_md204',1,'']]],
  ['target_20algorithm_1',['AOD Estimation (Dark Target Algorithm)',['../md_README.html#autotoc_md293',1,'']]],
  ['technical_20achievement_20strong_2',['technical achievement strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md131',1,'🎊 &lt;strong&gt;Technical Achievement&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md161',1,'🚀 &lt;strong&gt;Technical Achievement&lt;/strong&gt;']]],
  ['technical_20architecture_3',['Technical Architecture',['../md_PARALLEL__LUT__FINAL.html#autotoc_md138',1,'']]],
  ['technical_20architecture_20implemented_20strong_4',['🎯 &lt;strong&gt;Technical Architecture Implemented&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md116',1,'']]],
  ['technical_20details_5',['Technical Details',['../md_PARALLEL__LUT.html#autotoc_md98',1,'']]],
  ['technical_20implementation_6',['🛠️ Technical Implementation',['../md_OPENCL__SUMMARY.html#autotoc_md74',1,'']]],
  ['technical_20implementation_20strong_7',['🛠️ &lt;strong&gt;Technical Implementation&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md185',1,'']]],
  ['temperate_20mid_20summer_20e_20g_20mediterranean_20july_8',['Coastal temperate mid-summer (e.g. Mediterranean, July)',['../md_README.html#autotoc_md259',1,'']]],
  ['temperate_20mid_20winter_20e_20g_20paris_20january_9',['Continental urban temperate mid-winter (e.g. Paris, January)',['../md_README.html#autotoc_md258',1,'']]],
  ['term_20next_20version_10',['Short Term (Next Version)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md200',1,'']]],
  ['term_20research_11',['Long Term (Research)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md201',1,'']]],
  ['test_20categories_12',['Test Categories',['../md_PROGRAMMER__MANUAL.html#autotoc_md223',1,'']]],
  ['test_20coverage_13',['Test Coverage',['../md_PROGRAMMER__MANUAL.html#autotoc_md241',1,'']]],
  ['test_20script_14',['Test Script',['../md_PARALLEL__LUT.html#autotoc_md104',1,'']]],
  ['test_20suite_20structure_15',['Test Suite Structure',['../md_PROGRAMMER__MANUAL.html#autotoc_md221',1,'']]],
  ['tested_16',['Successfully Tested',['../md_OPENCL__SUMMARY.html#autotoc_md72',1,'']]],
  ['testing_17',['testing',['../md_PARALLEL__LUT.html#autotoc_md105',1,'Manual Testing'],['../md_PARALLEL__LUT.html#autotoc_md103',1,'Testing'],['../md_PROGRAMMER__MANUAL.html#autotoc_md220',1,'Testing'],['../md_README.html#autotoc_md284',1,'Testing']]],
  ['testing_20✅_18',['Integration Testing ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md127',1,'']]],
  ['testing_20results_19',['Testing Results',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md193',1,'']]],
  ['testing_20strong_20',['4. &lt;strong&gt;Documentation and Testing&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md157',1,'']]],
  ['tests_21',['tests',['../md_PROGRAMMER__MANUAL.html#autotoc_md225',1,'Integration Tests'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md171',1,'Module Tests'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md147',1,'Module Tests'],['../md_PROGRAMMER__MANUAL.html#autotoc_md226',1,'Performance Tests'],['../md_PROGRAMMER__MANUAL.html#autotoc_md222',1,'Running Tests'],['../md_PROGRAMMER__MANUAL.html#autotoc_md224',1,'Unit Tests']]],
  ['tests_20✅_22',['Module Tests ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md125',1,'']]],
  ['the_20tt_20g_20tt_20flag_23',['Runtime Generation with the &lt;tt&gt;-g&lt;/tt&gt; Flag',['../md_README.html#autotoc_md282',1,'']]],
  ['tips_24',['Performance Tips',['../md_OPENCL__INTEGRATION.html#autotoc_md59',1,'']]],
  ['tmp_25',['@page md_i_8hyper_8smac_8tmp i.hyper.smac.tmp',['..//home/yann/dev/i.hyper.smac/i.hyper.smac.tmp.md#autotoc_md34',1,'']]],
  ['to_20hyperspectral_20imagery_26',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['transformation_20achieved_27',['Transformation Achieved',['../md_PARALLEL__LUT__FINAL.html#autotoc_md137',1,'']]],
  ['tropical_20rainforest_20amazon_20congo_28',['Tropical rainforest (Amazon, Congo)',['../md_README.html#autotoc_md257',1,'']]],
  ['troubleshooting_29',['troubleshooting',['../md_PROGRAMMER__MANUAL.html#autotoc_md231',1,'Troubleshooting'],['../md_PARALLEL__LUT.html#autotoc_md106',1,'Troubleshooting'],['../md_OPENCL__INTEGRATION.html#autotoc_md54',1,'Troubleshooting'],['../i_hyper_smac.html#i_hyper_smac_troubleshooting',1,'Troubleshooting']]],
  ['tt_20apply_5flut_5fcorrection_20tt_30',['&lt;tt&gt;apply_lut_correction()&lt;/tt&gt;',['../md_PROGRAMMER__MANUAL.html#autotoc_md216',1,'']]],
  ['tt_20atmosphericlut_20tt_31',['&lt;tt&gt;AtmosphericLUT&lt;/tt&gt;',['../md_PROGRAMMER__MANUAL.html#autotoc_md218',1,'']]],
  ['tt_20g_20tt_20flag_32',['Runtime Generation with the &lt;tt&gt;-g&lt;/tt&gt; Flag',['../md_README.html#autotoc_md282',1,'']]],
  ['tt_20i_20hyper_20smac_20py_20tt_33',['tt i hyper smac py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md156',1,'3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)']]],
  ['tt_20lib_20lut_20py_20tt_34',['tt lib lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md155',1,'2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md180',1,'2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)']]],
  ['tt_20lib_20opencl_5faccelerator_20py_20tt_35',['1. OpenCL Accelerator Module (&lt;tt&gt;lib/opencl_accelerator.py&lt;/tt&gt;)',['../md_OPENCL__SUMMARY.html#autotoc_md67',1,'']]],
  ['tt_20lib_20parallel_5flut_20py_20tt_36',['tt lib parallel_lut py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'1. Parallel LUT Generator Module (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)']]],
  ['tt_20smac_5fcoef_5fgenerator_20py_20tt_37',['Generating Coefficients with &lt;tt&gt;smac_coef_generator.py&lt;/tt&gt;',['../md_README.html#autotoc_md278',1,'']]],
  ['tt_20smartlutmanager_20tt_38',['&lt;tt&gt;SmartLUTManager&lt;/tt&gt;',['../md_PROGRAMMER__MANUAL.html#autotoc_md219',1,'']]],
  ['tundra_20boreal_39',['Sub-arctic mid-summer — tundra / boreal',['../md_README.html#autotoc_md261',1,'']]],
  ['tuning_40',['tuning',['../md_PARALLEL__LUT.html#autotoc_md108',1,'Performance Tuning'],['../i_hyper_smac.html#i_hyper_smac_performance',1,'Performance Tuning']]],
  ['two_20stage_20atmospheric_20correction_20process_41',['Two-Stage Atmospheric Correction Process',['../md_i_8hyper_8smac.html#autotoc_md6',1,'']]]
];
