var searchData=
[
  ['sahara_20arabian_20peninsula_0',['Desert / arid land (Sahara, Arabian Peninsula)',['../md_README.html#autotoc_md252',1,'']]],
  ['script_1',['Test Script',['../md_PARALLEL__LUT.html#autotoc_md100',1,'']]],
  ['script_20integration_20strong_20tt_20i_20hyper_20smac_20py_20tt_2',['3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'']]],
  ['script_20integration_20tt_20i_20hyper_20smac_20py_20tt_3',['3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md177',1,'']]],
  ['see_20also_4',['see also',['../md_README.html#autotoc_md294',1,'See Also'],['../md_i_8hyper_8smac.html#autotoc_md32',1,'SEE ALSO']]],
  ['sensor_20configuration_5',['Sensor Configuration',['../md_i_8hyper_8smac.html#autotoc_md16',1,'']]],
  ['sensors_6',['Supported Sensors',['../md_README.html#autotoc_md262',1,'']]],
  ['setup_7',['setup',['../md_OPENCL__SUMMARY.html#autotoc_md78',1,'🔧 Installation and Setup'],['../md_PROGRAMMER__MANUAL.html#autotoc_md234',1,'Development Setup']]],
  ['short_20term_20next_20version_8',['Short Term (Next Version)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md196',1,'']]],
  ['single_20wavelength_9',['Single wavelength',['../md_README.html#autotoc_md275',1,'']]],
  ['smac_10',['smac',['../md_OPENCL__INTEGRATION.html',1,'OpenCL GPU Acceleration for i.hyper.smac'],['../md_PARALLEL__LUT.html',1,'Parallel LUT Generation for i.hyper.smac'],['../md_SMART__LUT__INTEGRATION.html',1,'Smart LUT Integration for i.hyper.smac']]],
  ['smac_20apply_20smac_20atmospheric_20correction_20to_20hyperspectral_20imagery_11',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['smac_20coefficient_20generation_12',['SMAC Coefficient Generation',['../md_README.html#autotoc_md272',1,'']]],
  ['smac_20equation_13',['SMAC Equation',['../md_README.html#autotoc_md282',1,'']]],
  ['smac_20programmer_20manual_14',['i.hyper.smac Programmer Manual',['../md_PROGRAMMER__MANUAL.html',1,'']]],
  ['smac_20py_20tt_15',['smac py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md177',1,'3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)']]],
  ['smac_20smac_20atmospheric_20correction_20for_20hyperspectral_20data_16',['i.hyper.smac - SMAC Atmospheric Correction for Hyperspectral Data',['../md_README.html',1,'']]],
  ['smac_20tmp_17',['i.hyper.smac.tmp',['../md_i_8hyper_8smac_8tmp.html',1,'']]],
  ['smac_3a_20hyperspectral_20atmospheric_20correction_20module_18',['i.hyper.smac: Hyperspectral Atmospheric Correction Module',['../i_hyper_smac.html',1,'']]],
  ['smac_5fcoef_5fgenerator_20py_20tt_19',['Generating Coefficients with &lt;tt&gt;smac_coef_generator.py&lt;/tt&gt;',['../md_README.html#autotoc_md274',1,'']]],
  ['smart_20lut_20behavior_20examples_20',['Smart LUT Behavior Examples',['../md_SMART__LUT__INTEGRATION.html#autotoc_md300',1,'']]],
  ['smart_20lut_20classes_21',['Smart LUT Classes',['../i_hyper_smac.html#i_hyper_smac_smart_lut_classes',1,'']]],
  ['smart_20lut_20integration_20for_20i_20hyper_20smac_22',['Smart LUT Integration for i.hyper.smac',['../md_SMART__LUT__INTEGRATION.html',1,'']]],
  ['smart_20lut_20system_23',['smart lut system',['../i_hyper_smac.html#i_hyper_smac_smart_lut',1,'Smart LUT System'],['../md_PROGRAMMER__MANUAL.html#autotoc_md224',1,'Smart LUT System']]],
  ['smartlutmanager_20tt_24',['&lt;tt&gt;SmartLUTManager&lt;/tt&gt;',['../md_PROGRAMMER__MANUAL.html#autotoc_md215',1,'']]],
  ['snow_25',['Sub-arctic mid-winter — boreal forest under snow',['../md_README.html#autotoc_md256',1,'']]],
  ['solution_20delivered_20strong_26',['🚀 &lt;strong&gt;Complete Solution Delivered&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md110',1,'']]],
  ['solved_27',['Problem Solved',['../md_SMART__LUT__INTEGRATION.html#autotoc_md297',1,'']]],
  ['spectral_20calibration_28',['Aerosol Spectral Calibration',['../md_README.html#autotoc_md285',1,'']]],
  ['speedup_20estimates_29',['Speedup Estimates',['../md_PARALLEL__LUT.html#autotoc_md87',1,'']]],
  ['speedup_20potential_30',['Speedup Potential',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md179',1,'']]],
  ['stage_20atmospheric_20correction_20process_31',['Two-Stage Atmospheric Correction Process',['../md_i_8hyper_8smac.html#autotoc_md6',1,'']]],
  ['status_32',['status',['../md_OPENCL__SUMMARY.html#autotoc_md82',1,'✅ Verification Status'],['../md_OPENCL__INTEGRATION.html#autotoc_md56',1,'Integration Status'],['../md_PARALLEL__LUT.html#autotoc_md98',1,'Integration Status']]],
  ['status_20strong_33',['status strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md109',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md130',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md187',1,'✅ &lt;strong&gt;Verification Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md166',1,'🔮 &lt;strong&gt;Verification Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md142',1,'🔮 &lt;strong&gt;Verification Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md120',1,'🔮 &lt;strong&gt;Verification Status&lt;/strong&gt;']]],
  ['status_3a_20complete_20strong_34',['status: complete strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md171',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md146',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md125',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;']]],
  ['steps_35',['steps',['../md_SMART__LUT__INTEGRATION.html#autotoc_md307',1,'Implementation Steps'],['../md_OPENCL__SUMMARY.html#autotoc_md80',1,'Installation Steps']]],
  ['strategy_36',['Fallback Strategy',['../md_OPENCL__INTEGRATION.html#autotoc_md48',1,'']]],
  ['strong_20achievement_20summary_20strong_37',['🏆 &lt;strong&gt;Achievement Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md198',1,'']]],
  ['strong_20complete_20solution_20delivered_20strong_38',['🚀 &lt;strong&gt;Complete Solution Delivered&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md110',1,'']]],
  ['strong_20core_20features_20delivered_20strong_39',['🚀 &lt;strong&gt;Core Features Delivered&lt;/strong&gt;',['../md_PARALLEL__LUT__FINAL.html#autotoc_md131',1,'']]],
  ['strong_20documentation_20and_20testing_20strong_40',['4. &lt;strong&gt;Documentation and Testing&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md153',1,'']]],
  ['strong_20documentation_20created_20strong_41',['strong documentation created strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md119',1,'📚 &lt;strong&gt;Documentation Created&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md141',1,'📚 &lt;strong&gt;Documentation Created&lt;/strong&gt;']]],
  ['strong_20documentation_20strong_42',['📚 &lt;strong&gt;Documentation&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md194',1,'']]],
  ['strong_20final_20achievement_20summary_20strong_43',['strong final achievement summary strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md124',1,'🏆 &lt;strong&gt;Final Achievement Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md145',1,'🏆 &lt;strong&gt;Final Achievement Summary&lt;/strong&gt;']]],
  ['strong_20final_20implementation_20status_20strong_44',['strong final implementation status strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md109',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md130',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;']]],
  ['strong_20future_20roadmap_20strong_45',['🔮 &lt;strong&gt;Future Roadmap&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md195',1,'']]],
  ['strong_20impact_20on_20users_20strong_46',['🎯 &lt;strong&gt;Impact on Users&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md191',1,'']]],
  ['strong_20impact_20summary_20strong_47',['🏆 &lt;strong&gt;Impact Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md126',1,'']]],
  ['strong_20implementation_20complete_20strong_48',['✅ &lt;strong&gt;IMPLEMENTATION COMPLETE&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md173',1,'']]],
  ['strong_20implementation_20summary_20strong_49',['🏆 &lt;strong&gt;Implementation Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md169',1,'']]],
  ['strong_20lut_20module_20integration_20strong_20tt_20lib_20lut_20py_20tt_50',['2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md151',1,'']]],
  ['strong_20main_20script_20integration_20strong_20tt_20i_20hyper_20smac_20py_20tt_51',['3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'']]],
  ['strong_20mission_20accomplished_20strong_52',['strong mission accomplished strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md148',1,'🎯 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md108',1,'📋 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md129',1,'📋 &lt;strong&gt;Mission Accomplished&lt;/strong&gt;']]],
  ['strong_20mission_20status_3a_20complete_20strong_53',['strong mission status: complete strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md171',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md146',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md125',1,'🎯 &lt;strong&gt;Mission Status: COMPLETE&lt;/strong&gt;']]],
  ['strong_20parallel_20lut_20generator_20module_20strong_20tt_20lib_20parallel_5flut_20py_20tt_54',['1. &lt;strong&gt;Parallel LUT Generator Module&lt;/strong&gt; (&lt;tt&gt;lib/parallel_lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md150',1,'']]],
  ['strong_20parallel_20lut_20implementation_20complete_20success_20strong_55',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['strong_20performance_20impact_20achieved_20strong_56',['📊 &lt;strong&gt;Performance Impact Achieved&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md111',1,'']]],
  ['strong_20performance_20impact_20strong_57',['strong performance impact strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md178',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md132',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;']]],
  ['strong_20technical_20achievement_20strong_58',['strong technical achievement strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md127',1,'🎊 &lt;strong&gt;Technical Achievement&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md157',1,'🚀 &lt;strong&gt;Technical Achievement&lt;/strong&gt;']]],
  ['strong_20technical_20architecture_20implemented_20strong_59',['🎯 &lt;strong&gt;Technical Architecture Implemented&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md112',1,'']]],
  ['strong_20technical_20implementation_20strong_60',['🛠️ &lt;strong&gt;Technical Implementation&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'']]],
  ['strong_20usage_20examples_20strong_61',['strong usage examples strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md162',1,'📋 &lt;strong&gt;Usage Examples&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md184',1,'📋 &lt;strong&gt;Usage Examples&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md116',1,'🚀 &lt;strong&gt;Usage Examples&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md138',1,'🚀 &lt;strong&gt;Usage Examples&lt;/strong&gt;']]],
  ['strong_20user_20benefits_20delivered_20strong_62',['strong user benefits delivered strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md113',1,'🎉 &lt;strong&gt;User Benefits Delivered&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md135',1,'🎯 &lt;strong&gt;User Benefits Delivered&lt;/strong&gt;']]],
  ['strong_20user_20benefits_20strong_63',['🎉 &lt;strong&gt;User Benefits&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md159',1,'']]],
  ['strong_20verification_20status_20strong_64',['strong verification status strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md187',1,'✅ &lt;strong&gt;Verification Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md142',1,'🔮 &lt;strong&gt;Verification Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md166',1,'🔮 &lt;strong&gt;Verification Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md120',1,'🔮 &lt;strong&gt;Verification Status&lt;/strong&gt;']]],
  ['strong_20what_20was_20delivered_20strong_65',['✅ &lt;strong&gt;What Was Delivered&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md149',1,'']]],
  ['strong_20what_20was_20implemented_20strong_66',['🚀 &lt;strong&gt;What Was Implemented&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md174',1,'']]],
  ['structure_67',['structure',['../md_PARALLEL__LUT.html#autotoc_md97',1,'File Structure'],['../md_README.html#autotoc_md244',1,'Project Structure'],['../md_PROGRAMMER__MANUAL.html#autotoc_md217',1,'Test Suite Structure']]],
  ['style_68',['style',['../md_PROGRAMMER__MANUAL.html#autotoc_md235',1,'Code Style'],['../md_README.html#autotoc_md283',1,'LUT Inversion (6S-style)']]],
  ['sub_20arctic_20mid_20summer_20—_20tundra_20boreal_69',['Sub-arctic mid-summer — tundra / boreal',['../md_README.html#autotoc_md257',1,'']]],
  ['sub_20arctic_20mid_20winter_20—_20boreal_20forest_20under_20snow_70',['Sub-arctic mid-winter — boreal forest under snow',['../md_README.html#autotoc_md256',1,'']]],
  ['submitting_20changes_71',['Submitting Changes',['../md_PROGRAMMER__MANUAL.html#autotoc_md236',1,'']]],
  ['success_72',['success',['../md_PARALLEL__LUT__SUCCESS.html',1,'✅ Parallel LUT Implementation SUCCESS'],['../md_PARALLEL__LUT__FINAL.html',1,'🎯 Parallel LUT Implementation - COMPLETE SUCCESS']]],
  ['success_20strong_73',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['successfully_20tested_74',['Successfully Tested',['../md_OPENCL__SUMMARY.html#autotoc_md68',1,'']]],
  ['suite_20structure_75',['Test Suite Structure',['../md_PROGRAMMER__MANUAL.html#autotoc_md217',1,'']]],
  ['summary_76',['summary',['../md_OPENCL__SUMMARY.html',1,'OpenCL Integration Summary'],['../md_PARALLEL__LUT__SUMMARY.html',1,'Parallel LUT Implementation Summary'],['../md_PARALLEL__LUT.html#autotoc_md106',1,'Summary']]],
  ['summary_20strong_77',['summary strong',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md198',1,'🏆 &lt;strong&gt;Achievement Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md124',1,'🏆 &lt;strong&gt;Final Achievement Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md145',1,'🏆 &lt;strong&gt;Final Achievement Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md126',1,'🏆 &lt;strong&gt;Impact Summary&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md169',1,'🏆 &lt;strong&gt;Implementation Summary&lt;/strong&gt;']]],
  ['summer_20—_20tundra_20boreal_78',['Sub-arctic mid-summer — tundra / boreal',['../md_README.html#autotoc_md257',1,'']]],
  ['summer_20e_20g_20mediterranean_20july_79',['Coastal temperate mid-summer (e.g. Mediterranean, July)',['../md_README.html#autotoc_md255',1,'']]],
  ['support_80',['Support',['../md_PROGRAMMER__MANUAL.html#autotoc_md240',1,'']]],
  ['supported_20devices_81',['Supported Devices',['../md_README.html#autotoc_md267',1,'']]],
  ['supported_20sensors_82',['Supported Sensors',['../md_README.html#autotoc_md262',1,'']]],
  ['surface_20prior_20and_20map_20estimate_83',['Surface Prior and MAP Estimate',['../md_README.html#autotoc_md287',1,'']]],
  ['swir_20h2o_20continuum_20accuracy_84',['SWIR H2O Continuum Accuracy',['../md_README.html#autotoc_md286',1,'']]],
  ['system_85',['system',['../md_PROGRAMMER__MANUAL.html#autotoc_md224',1,'Smart LUT System'],['../i_hyper_smac.html#i_hyper_smac_smart_lut',1,'Smart LUT System']]],
  ['system_20architecture_86',['system architecture',['../i_hyper_smac.html#i_hyper_smac_arch_overview',1,'System Architecture'],['../md_PROGRAMMER__MANUAL.html#autotoc_md208',1,'System Architecture']]],
  ['system_20requirements_87',['system requirements',['../md_OPENCL__INTEGRATION.html#autotoc_md37',1,'System Requirements'],['../md_PROGRAMMER__MANUAL.html#autotoc_md204',1,'System Requirements'],['../md_OPENCL__SUMMARY.html#autotoc_md79',1,'System Requirements'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md193',1,'System Requirements'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md161',1,'System Requirements']]],
  ['system_20requirements_20met_88',['system requirements met',['../md_PARALLEL__LUT__FINAL.html#autotoc_md137',1,'System Requirements Met'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md115',1,'System Requirements Met']]]
];
