var searchData=
[
  ['i_20hyper_20smac_0',['i hyper smac',['../md_OPENCL__INTEGRATION.html',1,'OpenCL GPU Acceleration for i.hyper.smac'],['../md_PARALLEL__LUT.html',1,'Parallel LUT Generation for i.hyper.smac'],['../md_SMART__LUT__INTEGRATION.html',1,'Smart LUT Integration for i.hyper.smac']]],
  ['i_20hyper_20smac_20apply_20smac_20atmospheric_20correction_20to_20hyperspectral_20imagery_1',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['i_20hyper_20smac_20programmer_20manual_2',['i.hyper.smac Programmer Manual',['../md_PROGRAMMER__MANUAL.html',1,'']]],
  ['i_20hyper_20smac_20py_20tt_3',['i hyper smac py tt',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md177',1,'3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)']]],
  ['i_20hyper_20smac_20smac_20atmospheric_20correction_20for_20hyperspectral_20data_4',['i.hyper.smac - SMAC Atmospheric Correction for Hyperspectral Data',['../md_README.html',1,'']]],
  ['i_20hyper_20smac_20tmp_5',['i.hyper.smac.tmp',['../md_i_8hyper_8smac_8tmp.html',1,'']]],
  ['i_20hyper_20smac_3a_20hyperspectral_20atmospheric_20correction_20module_6',['i.hyper.smac: Hyperspectral Atmospheric Correction Module',['../i_hyper_smac.html',1,'']]],
  ['imagery_7',['i.hyper.smac - Apply SMAC atmospheric correction to hyperspectral imagery',['../md_i_8hyper_8smac.html',1,'']]],
  ['immediate_20benefits_8',['Immediate Benefits',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md192',1,'']]],
  ['immediate_20impact_9',['immediate impact',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md160',1,'Immediate Impact'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md136',1,'Immediate Impact'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md114',1,'Immediate Impact']]],
  ['impact_10',['impact',['../md_OPENCL__SUMMARY.html#autotoc_md83',1,'🎯 Impact'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md114',1,'Immediate Impact'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md136',1,'Immediate Impact'],['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md160',1,'Immediate Impact']]],
  ['impact_20achieved_20strong_11',['📊 &lt;strong&gt;Performance Impact Achieved&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md111',1,'']]],
  ['impact_20on_20users_20strong_12',['🎯 &lt;strong&gt;Impact on Users&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md191',1,'']]],
  ['impact_20strong_13',['impact strong',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md154',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__FINAL.html#autotoc_md132',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md178',1,'📊 &lt;strong&gt;Performance Impact&lt;/strong&gt;']]],
  ['impact_20summary_20strong_14',['🏆 &lt;strong&gt;Impact Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md126',1,'']]],
  ['implementation_15',['implementation',['../md_OPENCL__SUMMARY.html#autotoc_md70',1,'🛠️ Technical Implementation'],['../md_PARALLEL__LUT.html#autotoc_md88',1,'Implementation']]],
  ['implementation_20complete_16',['✅ Implementation Complete',['../md_OPENCL__SUMMARY.html#autotoc_md61',1,'']]],
  ['implementation_20complete_20strong_17',['✅ &lt;strong&gt;IMPLEMENTATION COMPLETE&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md173',1,'']]],
  ['implementation_20complete_20success_18',['🎯 Parallel LUT Implementation - COMPLETE SUCCESS',['../md_PARALLEL__LUT__FINAL.html',1,'']]],
  ['implementation_20complete_20success_20strong_19',['🎯 &lt;strong&gt;PARALLEL LUT IMPLEMENTATION - COMPLETE SUCCESS&lt;/strong&gt;',['../md_PARALLEL__LUT__COMPLETE.html',1,'']]],
  ['implementation_20details_20',['Implementation Details',['../md_OPENCL__INTEGRATION.html#autotoc_md46',1,'']]],
  ['implementation_20status_20strong_21',['implementation status strong',['../md_PARALLEL__LUT__FINAL.html#autotoc_md130',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;'],['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md109',1,'✅ &lt;strong&gt;Final Implementation Status&lt;/strong&gt;']]],
  ['implementation_20steps_22',['Implementation Steps',['../md_SMART__LUT__INTEGRATION.html#autotoc_md307',1,'']]],
  ['implementation_20strong_23',['🛠️ &lt;strong&gt;Technical Implementation&lt;/strong&gt;',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md181',1,'']]],
  ['implementation_20success_24',['✅ Parallel LUT Implementation SUCCESS',['../md_PARALLEL__LUT__SUCCESS.html',1,'']]],
  ['implementation_20summary_25',['Parallel LUT Implementation Summary',['../md_PARALLEL__LUT__SUMMARY.html',1,'']]],
  ['implementation_20summary_20strong_26',['🏆 &lt;strong&gt;Implementation Summary&lt;/strong&gt;',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md169',1,'']]],
  ['implemented_27',['🚀 What Was Implemented',['../md_OPENCL__SUMMARY.html#autotoc_md62',1,'']]],
  ['implemented_20strong_28',['implemented strong',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md112',1,'🎯 &lt;strong&gt;Technical Architecture Implemented&lt;/strong&gt;'],['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md174',1,'🚀 &lt;strong&gt;What Was Implemented&lt;/strong&gt;']]],
  ['improvement_29',['Performance Improvement',['../md_SMART__LUT__INTEGRATION.html#autotoc_md298',1,'']]],
  ['improvements_30',['Expected Performance Improvements',['../md_OPENCL__SUMMARY.html#autotoc_md69',1,'']]],
  ['initialization_20fails_31',['OpenCL initialization fails',['../md_PROGRAMMER__MANUAL.html#autotoc_md230',1,'']]],
  ['inspired_20processing_32',['Full ISOFIT-Inspired Processing',['../md_README.html#autotoc_md258',1,'']]],
  ['inspired_20processing_20pipeline_33',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md271',1,'']]],
  ['installation_34',['installation',['../md_README.html#autotoc_md248',1,'Installation'],['../md_OPENCL__INTEGRATION.html#autotoc_md36',1,'Installation'],['../md_README.html#autotoc_md266',1,'Installation'],['../md_PROGRAMMER__MANUAL.html#autotoc_md203',1,'Installation'],['../md_README.html#autotoc_md250',1,'Manual Installation'],['../md_PROGRAMMER__MANUAL.html#autotoc_md206',1,'Module Installation']]],
  ['installation_20and_20setup_35',['🔧 Installation and Setup',['../md_OPENCL__SUMMARY.html#autotoc_md78',1,'']]],
  ['installation_20steps_36',['Installation Steps',['../md_OPENCL__SUMMARY.html#autotoc_md80',1,'']]],
  ['insufficient_20precision_37',['Example 2: Insufficient Precision',['../md_SMART__LUT__INTEGRATION.html#autotoc_md302',1,'']]],
  ['integration_38',['Module Integration',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md188',1,'']]],
  ['integration_20code_39',['Integration Code',['../md_SMART__LUT__INTEGRATION.html#autotoc_md299',1,'']]],
  ['integration_20for_20i_20hyper_20smac_40',['Smart LUT Integration for i.hyper.smac',['../md_SMART__LUT__INTEGRATION.html',1,'']]],
  ['integration_20status_41',['integration status',['../md_PARALLEL__LUT.html#autotoc_md98',1,'Integration Status'],['../md_OPENCL__INTEGRATION.html#autotoc_md56',1,'Integration Status']]],
  ['integration_20strong_20tt_20i_20hyper_20smac_20py_20tt_42',['3. &lt;strong&gt;Main Script Integration&lt;/strong&gt; (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md152',1,'']]],
  ['integration_20strong_20tt_20lib_20lut_20py_20tt_43',['2. &lt;strong&gt;LUT Module Integration&lt;/strong&gt; (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUCCESS.html#autotoc_md151',1,'']]],
  ['integration_20summary_44',['OpenCL Integration Summary',['../md_OPENCL__SUMMARY.html',1,'']]],
  ['integration_20testing_20✅_45',['Integration Testing ✅',['../md_PARALLEL__LUT__COMPLETE.html#autotoc_md123',1,'']]],
  ['integration_20tests_46',['Integration Tests',['../md_PROGRAMMER__MANUAL.html#autotoc_md221',1,'']]],
  ['integration_20tt_20i_20hyper_20smac_20py_20tt_47',['3. Main Script Integration (&lt;tt&gt;i.hyper.smac.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md177',1,'']]],
  ['integration_20tt_20lib_20lut_20py_20tt_48',['2. LUT Module Integration (&lt;tt&gt;lib/lut.py&lt;/tt&gt;)',['../md_PARALLEL__LUT__SUMMARY.html#autotoc_md176',1,'']]],
  ['integration_20with_20main_20workflow_49',['3. Integration with Main Workflow',['../md_OPENCL__SUMMARY.html#autotoc_md65',1,'']]],
  ['inversion_206s_20style_50',['LUT Inversion (6S-style)',['../md_README.html#autotoc_md283',1,'']]],
  ['isofit_20inspired_20processing_51',['Full ISOFIT-Inspired Processing',['../md_README.html#autotoc_md258',1,'']]],
  ['isofit_20inspired_20processing_20pipeline_52',['ISOFIT-Inspired Processing Pipeline',['../md_README.html#autotoc_md271',1,'']]],
  ['issues_53',['issues',['../md_PROGRAMMER__MANUAL.html#autotoc_md228',1,'Common Issues'],['../i_hyper_smac.html#i_hyper_smac_common_issues',1,'Common Issues'],['../md_OPENCL__INTEGRATION.html#autotoc_md51',1,'Common Issues'],['../md_PARALLEL__LUT.html#autotoc_md103',1,'Common Issues']]]
];
